---
title: "Session_2b"
author: "Jake Eisaguirre"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Library Packages
```{r}

library(tidyverse)
library(palmerpenguins)

```

##Plot a function inn `ggplot2`
```{r}

eq <- function(x) {
  
  3 * (x ^ 2) + 4
}

# Use stat_function()

ggplot(data = data.frame(x = c(1,100)), aes(x = x)) +
  stat_function(fun = eq)

```
### Task

plot $f(x)=2.4-5x^3+2.1x^2$

Over a range from -50 to +50

```{r}
func <- function(x){
  2.4 - (5 * x ^ 3) + (2.1 * x ^ 2)
}

ggplot(data = NULL) + stat_function(fun = func) +  xlim(min = -1, max = 100)


```
### `pennguins` body mass and flipper lenghts 

Basic ggplot scatterplot of body mass (y) annd flipper length (x)

```{r}

ggplot(data = penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color= species)) + 
  scale_color_manual(values = c("red", "purple", "cyan")) + 
  labs(x = 'flipper length (mm)', y = 'body mass (g)', title = 'palmer penguins size measurements') +
  facet_wrap(~island) +
  theme_dark()

```

### Higher order derivative 

```{r}
gt <- expression(2.2 + 3.1 * t - 5.6 * t ^ 4)

dg_dt <- D(expr = gt, 't')

dg_dt

d2g_dt2 <- D(expr = dg_dt, 't')

d2g_dt2

```

## Partial derivative

```{r}
f_xyz <- expression(2*x*y - 3*(x^2)*(z^3))

df_dx <- D(expr = f_xyz, 'x')

df_dx

df_dy <- D(expr = f_xyz, 'y')

df_dy

df_dz <- D(expr = f_xyz, 'z')

df_dz

```

